[package]
name = "gfx"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
cpal = { version = "0.16.0", features = ["jack"] }
env_logger = "0.11.8"
glam = { version = "0.30.9", features = ["bytemuck"] }
log = "0.4.28"
microfft = "0.6.0"
pollster = "0.4.0"
thingbuf = { version = "0.1.6", features = ["static"] }
thiserror = "2.0.17"
wgpu = "27.0.1"
winit = "0.30"
